# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad57343272deb61b9d591c9c695bbfcf9de4024e0cac9a49bacdd8671edfd4f36c12cce9f5c5057215c7655c6105b7d9cd3b325656f397528db8fc91c745ee7c

test:
  secret_key_base: 87f417ebdaba733cf7876af31a7db171cfee9a4e89820bc4d5c589c9ea4f57c5e6abc2f9c58273a945e64c19f831c0dc7b173b31f129879c48018803284f8487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
